services:
  api1: &api
    build: 
      context: .
      target: base
    container_name: api1
    volumes:
      - .:/app
    command: bash netcat.bash
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '100MB'
    networks:
      - rinhaBackendNetwork

  api2: 
    <<: *api
    container_name: api2

  nginx:
    image: nginx 
    container_name: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '50MB'
    networks:
      - rinhaBackendNetwork

networks:
  rinhaBackendNetwork: